version: '3'

volumes:
  datafiles:

services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - datafiles:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dockertutorial

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:80
    restart: always
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development